# Generated by Django 4.2 on 2024-05-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_alter_hospitalgallery_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="hospital.hospital",
            ),
            preserve_default=False,
        ),
    ]
