# Generated by Django 4.2 on 2024-05-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_doctor_hospital"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialty",
                to="hospital.specialty",
            ),
        ),
    ]
