# Generated by Django 4.2 on 2024-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_alter_doctor_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="visitors",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
